spring:
  datasource:
    url: jdbc:mysql://172.18.4.223:3306/policydemo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: FangKe@nwu123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  resources:
#    locations: file:F:\file

# mybatis 信息
#mybatis:
#  # 加载 Mybatis 映射文件
#  mapper-locations: classpath:mapper/**/*mapper.xml
#  # 配置下划线自动转驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true
server:
  port: 9090
  servlet:
    session:
      timeout: 172800
logging:
  level:
    com.demo.mapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.domain

geoserver:
  url: http://localhost:8081/geoserver/tongguan

# 文件上传相关
#file:
#  bucketName: def_bucket
#  local:
#    enable: true
##    base-path: /home/app/ws_demo/ws-files
#    base-path: F:/code/guotufiles
#    baseUrl: http://localhost:9090/profile



